In [1]:
import numpy as np

# Datatypes and Attribute

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
      [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 2, 2)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 8)

# Create a dataframe from a numpy array

In [12]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

 # Creating Arrays

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int64')

In [15]:
ones = np.ones((2,3))
ones               

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, (3,5))
random_array

array([[1, 9, 6, 7, 3],
       [2, 2, 0, 8, 7],
       [4, 4, 8, 7, 3]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
np.random.random((5,3))

array([[0.89328938, 0.48181437, 0.52617613],
       [0.00462923, 0.78317367, 0.64281276],
       [0.71675324, 0.58549852, 0.82925943],
       [0.03259285, 0.89627318, 0.47908865],
       [0.46660935, 0.86539055, 0.62686655]])

In [24]:
np.random.rand(5, 3)

array([[0.71930872, 0.02919177, 0.12057858],
       [0.02629416, 0.3844911 , 0.02927195],
       [0.55712842, 0.74314148, 0.66303844],
       [0.80194993, 0.55213266, 0.90514248],
       [0.46790921, 0.96538243, 0.24637686]])

In [25]:
np.random.seed(seed=7)
np.random.randint(10, size=(5, 3))

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

# Viewing arrays and matrices

In [26]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
a2[0]

array([1. , 2. , 3.3])

In [30]:
a2[1] 

array([4. , 5. , 6.5])

In [31]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
a3 [:1, :1, :2]

array([[[1, 2]]])

In [35]:
a3 [:2, :1, :2]

array([[[1, 2]],

       [[5, 6]]])

In [36]:
a3 [:2, :1, :1]

array([[[1]],

       [[5]]])

In [37]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7]],

        [[3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4]],

        [[3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0]]],


       [[[9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6]],

        [[9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4]]]])

In [39]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [47]:
#get first 3 digit of 1st row of last matrix
a4[1:2, 2:3, 0:1,:3]

array([[[[9, 8, 6]]]])

# Manupulating arrays

## Arithmetic

In [48]:
a1

array([1, 2, 3])

In [51]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [52]:
a1 + ones

array([2., 3., 4.])

In [53]:
a1 - ones

array([0., 1., 2.])

In [54]:
a1 * ones

array([1., 2., 3.])

In [55]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [56]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [57]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2,2) 

In [58]:
a1 / 1

array([1., 2., 3.])

In [59]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [60]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [61]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [62]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [63]:
np.add(a1, ones)

array([2., 3., 4.])

In [64]:
a1 

array([1, 2, 3])

In [65]:
a1 / 2

array([0.5, 1. , 1.5])

In [66]:
a1 % 2

array([1, 0, 1])

In [67]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [69]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation

In [70]:
a1

array([1, 2, 3])

In [71]:
sum(a1)

6

In [72]:
np.sum(a1)

6

In [73]:
massive_array = np.random.random(100000)
massive_array[:100]

array([0.39200156, 0.93959276, 0.21291858, 0.81329627, 0.40364858,
       0.58672092, 0.18599889, 0.81232251, 0.58084741, 0.44693254,
       0.79808141, 0.54427185, 0.41841659, 0.01915666, 0.68377373,
       0.48809792, 0.22057967, 0.55054305, 0.52259111, 0.48755248,
       0.26303148, 0.52728579, 0.98446573, 0.62342345, 0.62955693,
       0.9099729 , 0.96251949, 0.5850998 , 0.16489774, 0.39159332,
       0.94455493, 0.34339118, 0.70507037, 0.4628868 , 0.38679069,
       0.52843256, 0.82168992, 0.63847702, 0.86288872, 0.63662654,
       0.99929706, 0.51778008, 0.32761664, 0.09877324, 0.5667664 ,
       0.21520794, 0.01179079, 0.29921532, 0.03897743, 0.97621382,
       0.55145308, 0.07171621, 0.34006782, 0.24290239, 0.10735082,
       0.77033058, 0.35060155, 0.18764274, 0.91265269, 0.86114826,
       0.39889823, 0.54633644, 0.45037544, 0.69359919, 0.21384609,
       0.3237989 , 0.73989292, 0.18257051, 0.69602194, 0.52673506,
       0.19849106, 0.65046402, 0.50977649, 0.68903717, 0.57342

In [75]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

4.36 ms ± 125 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20 µs ± 9.98 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [76]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [81]:
np.mean(a2), a2.mean()

(3.6333333333333333, 3.6333333333333333)

In [82]:
np.max(a2), a2.max()

(6.5, 6.5)

In [83]:
np.mean(a2), a2.mean()

(3.6333333333333333, 3.6333333333333333)

In [84]:
np.std(a2)

1.8226964152656422

In [86]:
np.var(a2)

3.3222222222222224

# Reshape and Transpose

In [87]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [88]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [89]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2,2) 

In [91]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [93]:
a2_reshape[:, :2] * a3

array([[[ 1.,  2.],
        [ 6.,  8.]],

       [[20., 24.],
        [35., 40.]]])

In [94]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [95]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [96]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [97]:
a3.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

# Dot product

In [100]:
np.random.seed(0)

mat1 = np.random.randint(10, size =(5, 3))
mat2 = np.random.randint(10, size =(5, 3))
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [101]:
mat1 * mat2 #element wise multiplication

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [102]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [103]:
np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# Comparision Operators

In [104]:
a1

array([1, 2, 3])

In [105]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [106]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [107]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [108]:
a1 > 5

array([False, False, False])

In [109]:
a1 < 5

array([ True,  True,  True])

In [110]:
a1 == a1

array([ True,  True,  True])

In [111]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

# Sorting Array

In [112]:
random_array

array([[1, 9, 6, 7, 3],
       [2, 2, 0, 8, 7],
       [4, 4, 8, 7, 3]])

In [113]:
np.sort(random_array)

array([[1, 3, 6, 7, 9],
       [0, 2, 2, 7, 8],
       [3, 4, 4, 7, 8]])

In [114]:
np.argsort(random_array)

array([[0, 4, 2, 3, 1],
       [2, 0, 1, 4, 3],
       [4, 0, 1, 3, 2]])

In [116]:
np.argmin(random_array)

7

In [117]:
np.argmax(random_array)

1

In [118]:
np.argmax(random_array, axis=0)

array([2, 0, 2, 1, 1])

# Images as numpy array

<img src="images/panda.png"/>

In [120]:
from matplotlib.image import imread

panda = imread("images/panda.png")
type(panda)

numpy.ndarray

In [121]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [122]:
panda[:1]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)