In [1]:
import numpy as np

# Datatypes and Attribute

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1, 2, 3.3],
      [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
a3 = np.array([[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a1.shape

(3,)

In [15]:
a2.shape

(2, 3)

In [16]:
a3.shape

(2, 2, 2)

In [17]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [18]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [19]:
a1.size, a2.size, a3.size

(3, 6, 8)

# Create a dataframe from a numpy array

In [20]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

 # Creating Arrays

In [22]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int64')

In [24]:
ones = np.ones((2,3))
ones               

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [30]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [34]:
random_array = np.random.randint(0, 10, (3,5))
random_array

array([[7, 1, 6, 0, 5],
       [5, 8, 1, 8, 6],
       [2, 6, 7, 2, 3]])

In [35]:
random_array.size

15

In [36]:
random_array.shape

(3, 5)

In [38]:
np.random.random((5,3))

array([[1.66162450e-01, 7.01396765e-04, 7.02905052e-01],
       [7.42394208e-01, 5.01819374e-01, 7.52207064e-01],
       [8.64521656e-01, 1.36543083e-01, 6.08660046e-01],
       [1.02422523e-02, 8.46652365e-01, 6.87319136e-01],
       [8.53792810e-01, 5.15313724e-01, 5.14622447e-01]])

In [40]:
np.random.rand(5, 3)

array([[0.63782043, 0.98793206, 0.51797785],
       [0.43991866, 0.48846897, 0.50881889],
       [0.87487   , 0.4872372 , 0.77541543],
       [0.42741167, 0.81313235, 0.24005371],
       [0.75883267, 0.64283281, 0.9484637 ]])

In [50]:
np.random.seed(seed=7)
np.random.randint(10, size=(5, 3))

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

# Viewing arrays and matrices