In [1]:
import numpy as np

# Datatypes and Attribute

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3.3],
      [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2],
       [3, 4]],
      [[5, 6],
       [7, 8]]])
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 2, 2)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 8)

# Create a dataframe from a numpy array

In [12]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

 # Creating Arrays

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int64')

In [15]:
ones = np.ones((2,3))
ones               

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [18]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, (3,5))
random_array

array([[1, 9, 6, 7, 3],
       [2, 2, 0, 8, 7],
       [4, 4, 8, 7, 3]])

In [21]:
random_array.size

15

In [22]:
random_array.shape

(3, 5)

In [23]:
np.random.random((5,3))

array([[0.89328938, 0.48181437, 0.52617613],
       [0.00462923, 0.78317367, 0.64281276],
       [0.71675324, 0.58549852, 0.82925943],
       [0.03259285, 0.89627318, 0.47908865],
       [0.46660935, 0.86539055, 0.62686655]])

In [24]:
np.random.rand(5, 3)

array([[0.71930872, 0.02919177, 0.12057858],
       [0.02629416, 0.3844911 , 0.02927195],
       [0.55712842, 0.74314148, 0.66303844],
       [0.80194993, 0.55213266, 0.90514248],
       [0.46790921, 0.96538243, 0.24637686]])

In [25]:
np.random.seed(seed=7)
np.random.randint(10, size=(5, 3))

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

# Viewing arrays and matrices

In [26]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
a2[0]

array([1. , 2. , 3.3])

In [30]:
a2[1] 

array([4. , 5. , 6.5])

In [31]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [34]:
a3 [:1, :1, :2]

array([[[1, 2]]])

In [35]:
a3 [:2, :1, :2]

array([[[1, 2]],

       [[5, 6]]])

In [36]:
a3 [:2, :1, :1]

array([[[1]],

       [[5]]])

In [37]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 7, 0, 7, 6],
         [3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7]],

        [[3, 3, 8, 3, 0],
         [1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4]],

        [[3, 1, 3, 1, 3],
         [4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0]]],


       [[[9, 9, 3, 4, 5],
         [3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5]],

        [[7, 1, 5, 4, 4],
         [9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6]],

        [[9, 8, 6, 5, 9],
         [7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4]]]])

In [39]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [47]:
#get first 3 digit of 1st row of last matrix
a4[1:2, 2:3, 0:1,:3]

array([[[[9, 8, 6]]]])